---
# these tasks install php modules

- name: ensure php modules are installed
  apt:
    pkg: "{{item}}"
    update_cache: yes
  with_items: 
    - php
    - php-curl
    - php-mcrypt
    - php-gd
    - php-mysql
    - php-cli
    - php-memcache
    - php-intl
    - php-xdebug
    - php-xml
    - php-simplexml
    - php-zip

- name: configure php settings
  lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^{{ item.param }} =" line="{{ item.param }} = {{ item.value }}"
  with_items :
    - { param: 'error_reporting', value: 'E_ALL' }
    - { param: 'display_errors', value: 'On' }
    - { param: 'upload_max_filesize', value: '10M' }
    - { param: 'post_max_size', value: '10M' }
    - { param: 'max_execution_time', value: '240' }
    - { param: 'memory_limit', value: '512M' }
  notify : restart apache

- name: configure php xdebug
  lineinfile: dest=/etc/php/mods-available/xdebug.ini regexp="^{{ item.param }} =" line="{{ item.param }} = {{ item.value }}" create=yes mode=0644
  with_items :
    - { param: 'xdebug.remote_enable', value: '1' }
    - { param: 'xdebug.scream', value: '1' }
    - { param: 'xdebug.cli_color', value: '1' }
    - { param: 'xdebug.show_local_vars', value: '1' }
    - { param: 'xdebug.max_nesting_level', value: '400' }
  notify : restart apache

- name: set timezone
  lineinfile: dest=/etc/php/7.0/apache2/php.ini regexp="^[#|;]?date.timezone =" insertafter="^[#|;]?date.timezone =" line="date.timezone = {{ php.timezone }}"
  notify: restart apache

- name: set timezone php cli
  lineinfile: dest=/etc/php/7.0/cli/php.ini regexp="^[#|;]?date.timezone =" insertafter="^[#|;]?date.timezone =" line="date.timezone = {{ php.timezone }}"
  notify: restart apache
