- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  
  pre_tasks:
    - name: 'these pre_task install python2'
      raw: sudo apt-get -y install python-simplejson

  roles:
    - apt
    - apache
    - mysql
    - php
    - composer
    - mail
    - utils
    - prestashop
