---
# these tasks install composer

- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  when: prestashop.version.find('1.7') != -1

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
  when: prestashop.version.find('1.7') != -1

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
  when: prestashop.version.find('1.7') != -1

- name: make composer executable
  file: 
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  when: prestashop.version.find('1.7') != -1
